import React from 'react';
import { Shield, Lock, FileText, HelpCircle } from 'lucide-react';

export const Footer: React.FC = () => {
  return (
    <footer className="bg-slate-950 text-slate-400 border-t border-slate-800 py-8 px-4 mt-auto">
      <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
        <div>
          <div className="flex items-center gap-2 text-white font-bold mb-2 text-sm">
            <Shield className="w-4 h-4 text-amber-500" />
            <span>Rural Enterprise Advisory Portal (REVA)</span>
          </div>
          <p className="text-xs text-slate-400 leading-relaxed mb-3">
            An AI-driven hyper-local advisory and financial structuring engine developed for rural micro-entrepreneurs across India. Designed to deliver 10/90 capital structure analysis, scheme routing, and market intelligence.
          </p>
          <div className="flex items-center gap-2 text-[11px] text-slate-500">
            <Lock className="w-3 h-3 text-emerald-500" />
            <span>256-bit SSL Encrypted Advisory Service</span>
          </div>
        </div>

        <div>
          <h4 className="text-white font-semibold text-xs tracking-wider uppercase mb-3 text-amber-400">
            Government Scheme Routes Covered
          </h4>
          <ul className="space-[6px] text-xs">
            <li className="flex items-center gap-1.5 text-slate-300">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500"></span>
              <span>Micro Finance Support Route (≤ ₹1.40 Lakh | 6.5% p.a.)</span>
            </li>
            <li className="flex items-center gap-1.5 text-slate-300">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-500"></span>
              <span>Term Loan Enterprise Route (&gt; ₹1.40 Lakh to ₹50 Lakh | 8.0% p.a.)</span>
            </li>
            <li className="flex items-center gap-1.5 text-slate-400 mt-2">
              <FileText className="w-3 h-3 text-amber-500" />
              <span>NABARD &amp; RBI Priority Sector Lending Aligned</span>
            </li>
          </ul>
        </div>

        <div>
          <h4 className="text-white font-semibold text-xs tracking-wider uppercase mb-3 text-amber-400">
            Mandatory Advisory Disclaimer
          </h4>
          <p className="text-[11px] text-slate-400 leading-relaxed bg-slate-900 p-2.5 rounded border border-slate-800">
            <strong className="text-amber-400">Decision Support Notice:</strong> All financial calculations, project costs, scheme routings, and market feasibility scores generated by REVA are for guidance and decision support only. Sanctions, interest concessions, and loan approvals are subject to formal bank appraisal and official scheme guidelines.
          </p>
          <div className="flex items-center gap-2 text-xs text-slate-400 mt-3">
            <HelpCircle className="w-3.5 h-3.5 text-amber-400" />
            <span>Toll-Free Entrepreneur Helpline: 1800-11-2026 (Demo)</span>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto border-t border-slate-900 mt-6 pt-4 text-center text-[11px] text-slate-500">
        © 2026 Rural Enterprise Advisory Portal. Built for SIH 2026 Problem Statement. All rights reserved.
      </div>
    </footer>
  );
};
